const langs = [];

langs.en = {
  "files": "Files",
  "clock": "Clock",
  "calculator": "Calculator",
  "terminal": "Terminal",
  "web_browser": "Web browser",
  "settings": "Settings",
  "upload_btn": "Upload",
  "save_btn": "Save",
  "rename_btn": "Rename",
  "open_as_text_btn": "Open as text",
  "set_bg_btn": "Set BG",
  "prompt_delete": "Are you sure you want to delete \"{file}\"?",
  "loading_text": "Loading...",
  "delete_btn": "Delete",
  "prompt_new_file_name": "Enter the name for the new file:",
  "prompt_new_idb_name": "Enter name for new drive partition:",
  "alert_file_exists": "A file with this name already exists.",
  "alert_create_file_error": "Error saving the new file.",
  "prompt_rename": "Enter a new name for:",
  "js_error": "JavaScript Error!",
  "fs_error": "F/S Error",
  "unsupported_file_type": "Unsupported file type",
  "personalize": "Personalize",
  "general": "General",
  "language": "Language",
  "go": "Go",
  "reload": "Reload",
  "task_mgr": "Task Manager",
  "unknown": "Unknown",
  "cpu": "CPU",
  "ram": "RAM",
  "processes": "Processes",
  "restart": "Restart",
  "shutdown": "Shut Down",
  "copy_name": "Copy name",
  "autoload": "Open at login",
  "undo_btn": "Undo",
  "redo_btn": "Redo",
  "cut_btn": "Cut",
  "copy_btn": "Copy",
  "paste_btn": "Paste",
  "all_btn": "Select All",
  "keyboard": "Keyboard",
  "keyboard_set": "Shortcuts set:",
  "display": "Display",
  "display_type": "Display type:",
  "icons": "Icons",
  "desktop": "Desktop",
  "extract_btn": "Unpack",
  "info": "Information",
  "type": "Type",
  "size": "Size",
  "path": "Path",
  "modified": "Edited",
  "file_not_found": "File not found",
  "not_found": "Not found",
  "get_info": "Get Info",
  "dimensions": "Dimensions",
  "duration": "Duration",
  "pack_btn": "Pack",
  "ok": "OK",
  "cancel": "Cancel",
  "unmount_btn": "Unmount",
  "mount_btn": "Mount",
  "format_btn": "Format",
  "startup": "Startup disk",
  "print_btn": "Print",
  "drivers": "Drivers",
  "confirm": "Confirm",
  "prompt": "Prompt",
  "find_btn": "Find",
  "folder": "Folder",
  "about": "About",
  "memory": "Memory",
  "startup_disk": "Startup Disk",
  "theme": "Theme",
  "themes": "Themes",
  "confirm_set_theme": "Do you want to restart your device to fully install the theme?",
  "open": "Open",
  "devices": "Devices",
  "taskbar": "Panel",
  "taskbar_position": "Panel position",
  "top": "Top",
  "bottom": "Bottom",
  "low_batt_body":"Please connect charger.",
  "low_batt":"Low battery percentage!",
  "taskbar_items": "Panel items",
  "confirm_download": "Do you want to download \"{name}\"?",
  "device_connected": "Device connected",
  "device_disconnected": "Device disconnected",
  "add": "Add",
  "set_default": "Set as default",
  "show_hidden": "Show hidden files:",
  "usage": "Usage",
  "allow_usage": "Allow saving usage data locally",
  "show_bg_clock": "Fullscreen background clock"

};

langs.ua = {
  "files": "Файли",
  "clock": "Годинник",
  "calculator": "Калькулятор",
  "terminal": "Термінал",
  "web_browser": "Веб браузер",
  "settings": "Налаштування",
  "upload_btn": "Завантажити",
  "save_btn": "Зберегти",
  "rename_btn": "Перейменувати",
  "open_as_text_btn": "Відкр. як текст",
  "set_bg_btn": "Вст. як фон",
  "prompt_delete": "Ви впевнені, що хочете видалити \"{file}\"?",
  "loading_text": "Завантаження...",
  "delete_btn": "Видалити",
  "prompt_new_file_name": "Введіть ім'я:",
  "prompt_new_idb_name": "Введіть назву нового розділу диска:",
  "alert_file_exists": "Файл з таким іменем вже існує",
  "alert_create_file_error": "Помилка при збереженні нового файлу.",
  "prompt_rename": "Введіть нове ім'я:",
  "js_error": "Помилка JavaScript!",
  "fs_error": "Помилка f/s",
  "unsupported_file_type": "Непідтримуваний тип файлу",
  "personalize": "Персоналізація",
  "general": "Основне",
  "language": "Мова",
  "go": "Йти",
  "reload": "Оновити",
  "task_mgr": "Диспетчер завдань",
  "unknown": "Невідомий",
  "cpu": "ЦП",
  "ram": "ОЗП",
  "processes": "Процеси",
  "restart": "Перезавантажити",
  "shutdown": "Вимкнути",
  "copy_name": "Копіювати ім'я",
  "autoload": "Запускати при вході",
  "undo_btn": "Скасувати",
  "redo_btn": "Повторити",
  "cut_btn": "Вирізати",
  "copy_btn": "Копіювати",
  "paste_btn": "Вставити",
  "all_btn": "Виділити все",
  "keyboard": "Клавіатура",
  "keyboard_set": "Набір скорочень:",
  "display": "Дисплей",
  "display_type": "Тип дисплея:",
  "icons": "Значки",
  "desktop": "Стільниця",
  "extract_btn": "Розпакувати",
  "type": "Тип",
  "size": "Розмір",
  "path": "Шлях",
  "modified": "Змінено",
  "file_not_found": "Файл не знайдено",
  "not_found": "Не знайдено",
  "get_info": "Отримати інформацію",
  "info": "Інформація",
  "dimensions": "Розміри",
  "duration": "Тривалість",
  "pack_btn": "Запакувати",
  "ok": "ОК",
  "cancel": "Скасувати",
  "unmount_btn": "Відмонтувати",
  "mount_btn": "Змонтувати",
  "format_btn": "Форматувати",
  "startup": "Зробити завантажувальним",
  "print_btn": "Друк",
  "drivers": "Драйвери",
  "confirm": "Підтвердження",
  "prompt": "Запит",
  "find_btn": "Знайти",
  "folder": "Папка",
  "about": "Про систему",
  "memory": "Пам'ять",
  "startup_disk": "Завантажувальний диск",
  "theme": "Тема",
  "themes":"Теми",
  "confirm_set_theme": "Чи бажаєте перезавантажити пристрій для повного встановлення теми?",
  "open": "Відкрити",
  "devices": "Пристрої",
  "taskbar": "Панель",
  "taskbar_position": "Положення панелі",
  "top": "Зверху",
  "bottom": "Знизу",
  "taskbar_items": "Елементи панелі",
  "low_batt_body": "Будь ласка, підключіть зарядний пристрій.",
  "low_batt": "Низький відсоток заряду!",
  "confirm_download": "Ви хочете завантажити \"{name}\"?",
  "device_connected": "Пристрій підключено",
  "device_disconnected": "Пристрій відключено",
  "add": "Додати",
  "set_default": "Встановити за промовчанням",
  "show_hidden": "Показувати приховані файли:",
  "usage": "Використання",
  "allow_usage": "Дозволити локальне збереження телеметрії",
  "show_bg_clock": "Повноекранний годинник на тлі"

};

langs.fr = {
  "files": "Fichiers",
  "clock": "Horloge",
  "calculator": "Calculatrice",
  "terminal": "Terminal",
  "web_browser": "Navigateur Web",
  "settings": "Paramètres",
  "upload_btn": "Téléverser",
  "save_btn": "Enregistrer",
  "rename_btn": "Renommer",
  "open_as_text_btn": "Ouvrir comme texte",
  "set_bg_btn": "Définir le fond",
  "prompt_delete": "Voulez-vous vraiment supprimer \"{file}\"?",
  "loading_text": "Chargement...",
  "delete_btn": "Supprimer",
  "prompt_new_file_name": "Entrez le nom du nouveau fichier:",
  "prompt_new_idb_name": "Entrez le nom de la nouvelle partition:",
  "alert_file_exists": "Un fichier portant ce nom existe déjà.",
  "alert_create_file_error": "Erreur lors de l’enregistrement du fichier.",
  "prompt_rename": "Entrez un nouveau nom pour le:",
  "js_error": "Erreur JavaScript!",
  "fs_error": "Erreur système de fichiers",
  "unsupported_file_type": "Type de fichier non pris en charge",
  "personalize": "Personnalisation",
  "general": "Général",
  "language": "Langue",
  "go": "Aller",
  "reload": "Recharger",
  "task_mgr": "Gestionnaire des tâches",
  "unknown": "Inconnu",
  "cpu": "CPU",
  "ram": "RAM",
  "processes": "Processus",
  "restart": "Redémarrer",
  "shutdown": "Éteindre",
  "copy_name": "Copier le nom",
  "autoload": "Ouvrir au démarrage",
  "undo_btn": "Annuler",
  "redo_btn": "Rétablir",
  "cut_btn": "Couper",
  "copy_btn": "Copier",
  "paste_btn": "Coller",
  "all_btn": "Tout sélectionner",
  "keyboard": "Clavier",
  "keyboard_set": "Raccourcis définis:",
  "display": "Affichage",
  "display_type": "Type d’affichage:",
  "icons": "Icônes",
  "desktop": "Bureau",
  "extract_btn": "Extraire",
  "info": "Informations",
  "type": "Type",
  "size": "Taille",
  "path": "Chemin",
  "modified": "Modifié",
  "file_not_found": "Fichier introuvable",
  "not_found": "Introuvable",
  "get_info": "Lire les informations",
  "dimensions": "Dimensions",
  "duration": "Durée",
  "pack_btn": "Compresser",
  "ok": "OK",
  "cancel": "Annuler",
  "unmount_btn": "Démonter",
  "mount_btn": "Monter",
  "format_btn": "Formater",
  "startup": "Disque de démarrage",
  "print_btn": "Imprimer",
  "drivers": "Pilotes",
  "confirm": "Confirmer",
  "prompt": "Invite",
  "find_btn": "Rechercher",
  "folder": "Dossier",
  "about": "À propos",
  "memory": "Mémoire",
  "startup_disk": "Disque de démarrage",
  "theme": "Thème",
  "themes": "Thèmes",
  "confirm_set_theme": "Souhaitez-vous redémarrer votre appareil pour installer complètement le thème?",
  "open": "Ouvrir",
  "devices": "Appareils",
  "taskbar": "Barre",
  "taskbar_position": "Position de la barre:",
  "top": "Haut",
  "bottom": "Bas",
  "taskbar_items": "Elements de la barre",
  "low_batt_body": "Veuillez brancher le chargeur.",
  "low_batt": "Batterie faible !",
  "confirm_download": "Voulez-vous télécharger \"{name}\" ?",
  "device_connected": "Appareil connecté",
  "device_disconnected": "Appareil déconnecté",
  "add": "Ajouter",
  "set_default": "Définir comme valeur par défaut",
  "show_hidden": "Afficher les fichiers cachés:",
  "usage": "Utilisation",
  "allow_usage": "Autoriser la télémétrie locale de l'OS",
  "show_bg_clock": "Horloge plein écran en arrière-plan"

};

langs.ru = {
  "files": "Файлы",
  "clock": "Часы",
  "calculator": "Калькулятор",
  "terminal": "Терминал",
  "web_browser": "Браузер",
  "settings": "Настройки",
  "upload_btn": "Загрузить",
  "save_btn": "Сохранить",
  "rename_btn": "Переименовать",
  "open_as_text_btn": "Откр.как текст",
  "set_bg_btn": "Сделать фоном",
  "prompt_delete": "Удалить \"{file}\"?",
  "loading_text": "Загрузка...",
  "delete_btn": "Удалить",
  "prompt_new_file_name": "Введите имя:",
  "prompt_new_idb_name": "Имя нового раздела:",
  "alert_file_exists": "Файл уже существует",
  "alert_create_file_error": "Ошибка сохранения файла",
  "prompt_rename": "Новое имя для:",
  "js_error": "Ошибка JavaScript!",
  "fs_error": "Ошибка FS",
  "unsupported_file_type": "Тип файла не поддерживается",
  "personalize": "Персонализация",
  "general": "Основные",
  "language": "Язык",
  "go": "Перейти",
  "reload": "Обновить",
  "task_mgr": "Диспетчер задач",
  "unknown": "Неизвестно",
  "cpu": "ЦП",
  "ram": "ОЗУ",
  "processes": "Процессы",
  "restart": "Перезагрузить",
  "shutdown": "Выключить",
  "copy_name": "Копировать имя",
  "autoload": "Запускать при входе",
  "undo_btn": "Отменить",
  "redo_btn": "Повторить",
  "cut_btn": "Вырезать",
  "copy_btn": "Копировать",
  "paste_btn": "Вставить",
  "all_btn": "Выделить всё",
  "keyboard": "Клавиатура",
  "keyboard_set": "Набор сокращений:",
  "display": "Дисплей",
  "display_type": "Тип дисплея:",
  "icons": "Значки",
  "desktop": "Рабочий стол",
  "extract_btn": "Распаковать",
  "info": "Информация",
  "type": "Тип",
  "size": "Размер",
  "path": "Путь",
  "modified": "Изменен",
  "file_not_found": "Файл не найден",
  "not_found": "Не найдено",
  "get_info": "Свойства",
  "dimensions": "Размеры",
  "duration": "Длительность",
  "pack_btn": "Упаковать",
  "ok": "ОК",
  "cancel": "Отмена",
  "unmount_btn": "Размонтировать",
  "mount_btn": "Монтировать",
  "format_btn": "Форматировать",
  "startup": "Сделать загрузочным",
  "print_btn": "Печать",
  "drivers": "Драйверы",
  "confirm": "Подтверждение",
  "prompt": "Запрос",
  "find_btn": "Найти",
  "folder": "Папка",
  "about": "О системе",
  "memory": "Память",
  "startup_disk": "Загрузочный диск",
  "theme": "Тема",
  "themes":"Темы",
  "confirm_set_theme": "Хотите перезагрузить устройство для полной установки темы?",
  "open": "Открыть",
  "devices": "Устройства",
  "taskbar": "Панель",
  "taskbar_position": "Расположение панели:",
  "top": "Сверху",
  "bottom": "Снизу",
  "taskbar_items": "Элементы панели",
  "low_batt_body": "Пожалуйста, подключите зарядное устройство.",
  "low_batt": "Низкий заряд батареи!",
  "confirm_download": "Вы хотите загрузить \"{name}\"?",
  "device_connected": "Устройство подключено",
  "device_disconnected": "Устройство отключено",
  "add":"Добавить",
  "set_default": "Установить по умолчанию",
  "show_hidden": "Показывать скрытые файлы:",
  "usage": "Использование",
  "allow_usage": "Разрешить локальное сохранение телеметрии",
  "show_bg_clock": "Полноэкранные часы на фоне"
};

langs.pl = {
  "files": "Pliki",
  "clock": "Zegar",
  "calculator": "Kalkulator",
  "terminal": "Terminal",
  "web_browser": "Przeglądarka internetowa",
  "settings": "Ustawienia",
  "upload_btn": "Prześlij",
  "save_btn": "Zapisz",
  "rename_btn": "Zmień nazwę",
  "open_as_text_btn": "Otwórz jako tekst",
  "set_bg_btn": "Ustaw jako tło",
  "prompt_delete": "Czy na pewno chcesz usunąć \"{file}\"?",
  "loading_text": "Ładowanie...",
  "delete_btn": "Usuń",
  "prompt_new_file_name": "Wprowadź nazwę:",
  "prompt_new_idb_name": "Wprowadź nazwę nowej partycji dysku:",
  "alert_file_exists": "Plik o takiej nazwie już istnieje",
  "alert_create_file_error": "Błąd podczas zapisywania nowego pliku.",
  "prompt_rename": "Wprowadź nową nazwę:",
  "js_error": "Błąd JavaScript!",
  "fs_error": "Błąd f/s",
  "unsupported_file_type": "Nieobsługiwany typ pliku",
  "personalize": "Personalizacja",
  "general": "Ogólne",
  "language": "Język",
  "go": "Przejdź",
  "reload": "Odśwież",
  "task_mgr": "Menedżer zadań",
  "unknown": "Nieznany",
  "cpu": "CPU",
  "ram": "RAM",
  "processes": "Procesy",
  "restart": "Uruchom ponownie",
  "shutdown": "Wyłącz",
  "copy_name": "Kopiuj nazwę",
  "autoload": "Uruchamiaj przy starcie",
  "undo_btn": "Cofnij",
  "redo_btn": "Ponów",
  "cut_btn": "Wytnij",
  "copy_btn": "Kopiuj",
  "paste_btn": "Wklej",
  "all_btn": "Zaznacz wszystko",
  "keyboard": "Klawiatura",
  "keyboard_set": "Zestaw skrótów:",
  "display": "Ekran",
  "display_type": "Typ ekranu:",
  "icons": "Ikony",
  "desktop": "Pulpit",
  "extract_btn": "Rozpakuj",
  "info": "Informacje",
  "type": "Typ",
  "size": "Rozmiar",
  "path": "Ścieżka",
  "modified": "Zmodyfikowano",
  "file_not_found": "Nie znaleziono pliku",
  "not_found": "Nie znaleziono",
  "get_info": "Pokaż informacje",
  "dimensions": "Wymiary",
  "duration": "Czas trwania",
  "pack_btn": "Spakuj",
  "ok": "OK",
  "cancel": "Anuluj",
  "unmount_btn": "Odmontuj",
  "mount_btn": "Zamontuj",
  "format_btn": "Formatuj",
  "startup": "Uczyń rozruchowym",
  "print_btn": "Drukuj",
  "drivers": "Sterowniki",
  "confirm": "Potwierdzenie",
  "prompt": "Monit",
  "find_btn": "Znajdź",
  "folder": "Folder",
  "about": "O systemie",
  "memory": "Pamięć",
  "startup_disk": "Dysk rozruchowy",
  "theme": "Motyw",
  "themes": "Motywy",
  "confirm_set_theme": "Czy chcesz ponownie uruchomić urządzenie, aby w pełni zastosować motyw?",
  "open": "Otwórz",
  "devices": "Urządzenia",
  "taskbar": "Panel",
  "taskbar_position": "Pozycja panelu",
  "top": "Na górze",
  "bottom": "Na dole",
  "taskbar_items": "Elementy panelu",
  "low_batt_body": "Proszę podłączyć ładowarkę.",
  "low_batt": "Niski poziom baterii!",
  "confirm_download": "Czy chcesz pobrać \"{name}\"?",
  "device_connected": "Urządzenie podłączone",
  "device_disconnected": "Urządzenie odłączone",
  "add": "Dodaj",
  "set_default": "Ustaw jako domyślne",
  "show_hidden": "Pokaż ukryte pliki:",
  "usage": "Użycie",
  "allow_usage": "Zezwalaj na lokalne zapisywanie telemetryczne",
  "show_bg_clock": "Pełnoekranowy zegar w tle"
};